apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hwwr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hwwr
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hwwr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hwwr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hwwr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tywi-tenant/rhtap-demo-app/hacbs-test-project-hwwr@sha256:6efcb3770a028f1342b514addc73d3d99624233722c53c0f3ace2746e15474b2
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
